# nom de l'assistant
name: Verification du Projet esuggest

# quand travailler ?
on: [push] # dès que le code est envoyé (push) sur GitHub

# quoi faire ?
jobs:
    verification-basique:
        runs-on: ubuntu-latest # utilises un ordinateur sous Linux
        steps:
            - name: Recuperer le cdoe
              uses: actions/checkout@v4 # copy-paste du code
            
            - name: Installer PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.5' # même version installée

            - name: Verifier l'installation
              run: composer install --no-scripts # vérifie que tout fonctionne
